package server.handlers;

public enum Endpoint {
    GET_TASKS,
    GET_TASK,
    ADD_TASK,
    UPDATE_TASK,
    DELETE_TASK,
    GET_SUBTASKS,
    GET_SUBTASK,
    ADD_SUBTASK,
    UPDATE_SUBTASK,
    DELETE_SUBTASK,
    GET_EPICS,
    GET_EPIC,
    GET_EPIC_SUBTASKS,
    ADD_EPIC,
    DELETE_EPIC,
    GET_HISTORY,
    GET_PRIORITIZED_TASKS,
    UNKNOWN
}
